const productsTypes = {
  ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  SET_PRODUCTS: 'SET_PRODUCTS',
  DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
  FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
  SET_PRODUCT: 'SET_PRODUCT',
  FETCH_SOME_PRODUCTS_START: 'FETCH_SOME_PRODUCTS_START',
  SET_SOME_PRODUCTS:'SET_SOME_PRODUCTS',
  FETCH_FOOTER_PRODUCT_START: 'FETCH_FOOTER_PRODUCT_START',
  SET_FOOTER_PRODUCT:'SET_FOOTER_PRODUCT',
};

export default productsTypes;